[build-system]
requires = ["setuptools>=80", "setuptools-scm[simple]>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "nightlies"
dynamic = ["version"]
description = "CLI for querying nightly logs and reports"
readme = "README.md"
authors = [
    { name = "Pavel Panchekha", email = "me@pavpanchekha.com" },
]
requires-python = ">=3.12"
license = "MIT"
license-files = ["LICENSE"]
keywords = ["nightlies", "cli", "logs", "reports"]
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "Topic :: Utilities",
]
[project.urls]
Homepage = "https://github.com/pavpanchekha/nightlies"
Repository = "https://github.com/pavpanchekha/nightlies"
Issues = "https://github.com/pavpanchekha/nightlies/issues"

[project.scripts]
nightlies = "cli:main"

[project.optional-dependencies]
server = [
    "bottle>=0.13.4",
]

[tool.setuptools]
py-modules = ["cli"]

[dependency-groups]
dev = [
    "mypy>=1.20.1",
]
